# -*- coding: utf-8 -*-
"""Sistem Panen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nOuNyuONcYV11KITIkfAfUDmms_c_CU
"""

# Program Penghitung Total Hasil Panen

hasil_panen = {
    "Padi": 500,
    "Jagung": 300,
    "Kedelai": 200
}

total_panen = sum(hasil_panen.values())

print("Total hasil panen:", total_panen, "kg")