# -*- coding: utf-8 -*-
"""Sistem Panen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nOuNyuONcYV11KITIkfAfUDmms_c_CU
"""

# Program Penghitung Total Hasil Panen

hasil_panen = {
    "Padi": 500,
    "Jagung": 300,
    "Kedelai": 200
}

total_panen = sum(hasil_panen.values())

print("Total hasil panen:", total_panen, "kg")
# Fungsi perhitungan diskon
def hitung_diskon(harga, persen_diskon):
    diskon = harga * persen_diskon / 100
    harga_akhir = harga - diskon
    return harga_akhir

harga = 100000
persen_diskon = 10

harga_setelah_diskon = hitung_diskon(harga, persen_diskon)

print("Harga setelah diskon:",
      harga_setelah_diskon)
